language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: vincenzoviscontiii
    token:
      secure: a53452ea9d310f32e90f9cece0dd1e8702cf0c97
script:
- ant build
- sonar-scanner



